import {
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  Bell,
  Box,
  Brain,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Cloud,
  Code2,
  Cpu,
  Database,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Globe,
  Home,
  Image as ImageIcon,
  Layers,
  Leaf,
  Link2,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  Moon,
  Network,
  Package,
  Palette,
  Pencil,
  Play,
  Plus,
  ScanLine,
  Search,
  Settings,
  Shield,
  Sparkles,
  Sun,
  Target,
  Terminal,
  TrendingUp,
  Trash2,
  Upload,
  User,
  Users,
  Workflow,
  X,
  Zap,
  LayoutGrid,
  type LucideProps,
} from "lucide-react";

/**
 * String-keyed icon registry.
 *
 * Data files reference icons by name so they stay serialisable and can be
 * stored and returned verbatim by the server without importing components.
 */
export const ICONS = {
  activity: Activity,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  bell: Bell,
  box: Box,
  brain: Brain,
  building: Building2,
  calendar: Calendar,
  chart: BarChart3,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  clock: Clock,
  cloud: Cloud,
  code: Code2,
  cpu: Cpu,
  database: Database,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  file: FileText,
  filter: Filter,
  globe: Globe,
  grid: LayoutGrid,
  home: Home,
  image: ImageIcon,
  layers: Layers,
  leaf: Leaf,
  link: Link2,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  message: MessageSquare,
  moon: Moon,
  network: Network,
  package: Package,
  palette: Palette,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  scan: ScanLine,
  search: Search,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  sun: Sun,
  target: Target,
  terminal: Terminal,
  trash: Trash2,
  trending: TrendingUp,
  upload: Upload,
  user: User,
  users: Users,
  workflow: Workflow,
  x: X,
  zap: Zap,
} as const;

export type IconName = keyof typeof ICONS;

interface IconProps extends LucideProps {
  name: string;
}

export function Icon({ name, ...props }: IconProps) {
  const Component = ICONS[name as IconName] ?? Box;
  return <Component {...props} />;
}
